services:
  app:
    extends:
      file: docker-compose.prod.yml
      service: app
    build:
      context: .
      dockerfile: Dockerfile
    # Allow container to access Host machine (Laragon DB)
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # Force DB_HOST to point to the host machine
      - DB_HOST=host.docker.internal
    ports:
      # Use a different port to avoid conflict with dev (9001) or Laragon (80)
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  public_data:
